### ISSUE TITLE
Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by cocker-cc** [piotrmurach/tty-editor#2]
With Ruby 2.7.0 I encounter the following Warning-Message:  
```
~/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/tty-editor-0.5.1/lib/tty/editor.rb:90: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

A quick Search provides the Reason for this Warning:  
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by piotrmurach** [comment]
This is fixed in the master branch and will be released with the `v0.6.0`. I'd appreciate it if you can test against the master branch. As for the release, I'd expect to finish things soon.

**Comment by thomas-merz** [comment]
@piotrmurach : When can I find v0.6.0 ready to be installed/updated via "gem update tty-editor"?

**Comment by piotrmurach** [comment]
@thomas-merz Thanks for using `tty-editor` and asking for an update. I've got `tty-command`, `tty-table`, `tty-editor`, `tty-progressbar` left to update out of 26 `tty` gems. I hope to get to it soon but I don't want to promise a date.

**Comment by piotrmurach** [comment]
@thomas-merz Thanks for using `tty-editor` and asking for an update. I've got `tty-command`, `tty-table`, `tty-editor`, `tty-progressbar` left to update out of 26 `tty` gems. I hope to get to it soon but I don't want to promise a date.

**Comment by piotrmurach** [comment]
@thomas-merz Released `v0.6.0`. Hope you like it!

**Comment by thomas-merz** [comment]
@piotrmurach  awesome and many thanks! Warning is gone now! Can I buy you a beer or coffee? :-)

**Comment by piotrmurach** [comment]
@thomas-merz In place of beer or cofee, you could consider [sponsoring](https://github.com/sponsors/piotrmurach) my open-source work which I'd really appreciate. This would help me continue working on projects like [ttytoolkit.org](https://ttytoolkit.org/), [rspec-benchmark](https://github.com/piotrmurach/rspec-benchmark), [finite_machine](https://github.com/piotrmurach/finite_machine) and many more.
